apiVersion: v1
kind: Service
metadata:
  name: wes-audio-server
spec:
  selector:
    app: wes-audio-server
  ports:
    - name: pulseaudio
      protocol: TCP
      port: 4713
      targetPort: 4713
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wes-audio-server-pulse-config
data:
  default.pa: |
    load-module module-device-restore
    load-module module-stream-restore
    load-module module-card-restore
    load-module module-augment-properties
    load-module module-switch-on-port-available
    
    # we try to detect USB audio devices automatically
    load-module module-udev-detect
    
    # fallbacks, we try to load USB audio card found at common positions
    .ifexists /proc/asound/card2
    load-module module-alsa-card device_id=2 name=usb_audio_card
    .endif
    
    .ifexists /proc/asound/card3
    load-module module-alsa-card device_id=3 name=usb_audio_card_alt
    .endif
    
    load-module module-native-protcol-unix
    load-module module-native-protocol-tcp auth-anonymous=1
    
    load-module module-default-device-restore
    load-module module-rescue-streams
    load-module module-always-sink
    load-module module-intended-roles
    load-module module-filter-heuristics
    load-module module-filter-apply
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-audio-server
spec:
  selector:
    matchLabels:
      app: wes-audio-server
  template:
    metadata:
      labels:
        app: wes-audio-server
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        resource.microphone: "true"
      hostNetwork: true
      containers:
        - name: wes-audio-server
          image: waggle/wes-audio-server:0.3.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 200m
              memory: 20Mi
          ports:
            - containerPort: 4713
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev-snd
              mountPath: /dev/snd
            - name: dev-bus-usb
              mountPath: /dev/bus/usb
            - name: pulse-config
              mountPath: /etc/pulse/default.pa
              subPath: default.pa
          env:
            - name: USB_AUDIO_DETECTION_MODE
              value: "auto"  
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  # check for USB audio devices 
                  pactl list sources | grep 'alsa.name = "USB Audio"' || \
                  pactl list sources | grep 'alsa.driver_name = "snd_usb_audio"' || \
                  pactl list sources | grep 'device.icon_name = "audio-input-microphone"'
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: dev-snd
          hostPath:
            path: /dev/snd
        - name: dev-bus-usb
          hostPath:
            path: /dev/bus/usb
        - name: pulse-config
          configMap:
            name: wes-audio-server-pulse-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wes-audio-server-plugin-conf
data:
  asound.conf: |
    pcm.pulse {
        type pulse
    }
    ctl.pulse {
        type pulse
    }
    pcm.!default {
        type pulse
    }
    ctl.!default {
        type pulse
    }